/* Generated By:JJTree: Do not edit this line. ASTfunparam.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunparam extends SimpleNode {
  public ASTfunparam(int id) {
    super(id);
  }

  public ASTfunparam(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9c40460f97494f4f8dd291f8c6a050cc (do not edit this line) */
