/* Generated By:JJTree: Do not edit this line. ASTforeach_stat.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTforeach_stat extends SimpleNode {
  public ASTforeach_stat(int id) {
    super(id);
  }

  public ASTforeach_stat(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a03c1b5285361f7af2903a60e48ca9f8 (do not edit this line) */
