/* Generated By:JJTree: Do not edit this line. ASTparam_decls.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparam_decls extends SimpleNode {
  public ASTparam_decls(int id) {
    super(id);
  }

  public ASTparam_decls(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7ce0e14e69fdc502c0cb5c10b239ca1e (do not edit this line) */
