/* Generated By:JJTree: Do not edit this line. ASTreturn_stat.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreturn_stat extends SimpleNode {
  public ASTreturn_stat(int id) {
    super(id);
  }

  public ASTreturn_stat(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b65a0dff11e80aa7c9b1f857a8482279 (do not edit this line) */
