/* Generated By:JJTree: Do not edit this line. ASTwhile_stat.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTwhile_stat extends SimpleNode {
  public ASTwhile_stat(int id) {
    super(id);
  }

  public ASTwhile_stat(HL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HLVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3e9555a88f3a31ebe541ae1740900985 (do not edit this line) */
