/* Generated By:JavaCC: Do not edit this line. HLDefaultVisitor.java Version 7.0.10 */
public class HLDefaultVisitor implements HLVisitor{
  public Object defaultVisit(SimpleNode node, Object data) throws Exception{
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTvar_decl node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTfn_decl node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTparam_decls node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTvarparam node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTfunparam node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTbody node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTassignment node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTif_stat node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTNULL node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTclause node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTfor_stat node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTforeach_stat node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTwhile_stat node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTfn_call node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTparameters node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTreturn_stat node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTprint_stat node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTprintln_stat node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTor node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTand node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTnot node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTcomparison node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTLT node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTLE node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTGT node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTGE node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTEQ node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTNE node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTisint node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTispol node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTisfun node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTsum node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTplus node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTminus node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTproduct node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTtimes node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTdiv node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTeval node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTpolyn node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTidentifier node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTinteger node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTstring node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTbool node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=ed113a1d584a7bc734e1171b755e1354 (do not edit this line) */
