/* Generated By:JavaCC: Do not edit this line. HLTreeConstants.java Version 7.0.10 */
public interface HLTreeConstants
{
  public int JJTVOID = 0;
  public int JJTVAR_DECL = 1;
  public int JJTFN_DECL = 2;
  public int JJTPARAM_DECLS = 3;
  public int JJTVARPARAM = 4;
  public int JJTFUNPARAM = 5;
  public int JJTBODY = 6;
  public int JJTASSIGNMENT = 7;
  public int JJTIF_STAT = 8;
  public int JJTNULL = 9;
  public int JJTCLAUSE = 10;
  public int JJTFOR_STAT = 11;
  public int JJTFOREACH_STAT = 12;
  public int JJTWHILE_STAT = 13;
  public int JJTFN_CALL = 14;
  public int JJTPARAMETERS = 15;
  public int JJTRETURN_STAT = 16;
  public int JJTPRINT_STAT = 17;
  public int JJTPRINTLN_STAT = 18;
  public int JJTOR = 19;
  public int JJTAND = 20;
  public int JJTNOT = 21;
  public int JJTCOMPARISON = 22;
  public int JJTLT = 23;
  public int JJTLE = 24;
  public int JJTGT = 25;
  public int JJTGE = 26;
  public int JJTEQ = 27;
  public int JJTNE = 28;
  public int JJTISINT = 29;
  public int JJTISPOL = 30;
  public int JJTISFUN = 31;
  public int JJTSUM = 32;
  public int JJTPLUS = 33;
  public int JJTMINUS = 34;
  public int JJTPRODUCT = 35;
  public int JJTTIMES = 36;
  public int JJTDIV = 37;
  public int JJTEVAL = 38;
  public int JJTPOLYN = 39;
  public int JJTIDENTIFIER = 40;
  public int JJTINTEGER = 41;
  public int JJTSTRING = 42;
  public int JJTBOOL = 43;


  public String[] jjtNodeName = {
    "void",
    "var_decl",
    "fn_decl",
    "param_decls",
    "varparam",
    "funparam",
    "body",
    "assignment",
    "if_stat",
    "NULL",
    "clause",
    "for_stat",
    "foreach_stat",
    "while_stat",
    "fn_call",
    "parameters",
    "return_stat",
    "print_stat",
    "println_stat",
    "or",
    "and",
    "not",
    "comparison",
    "LT",
    "LE",
    "GT",
    "GE",
    "EQ",
    "NE",
    "isint",
    "ispol",
    "isfun",
    "sum",
    "plus",
    "minus",
    "product",
    "times",
    "div",
    "eval",
    "polyn",
    "identifier",
    "integer",
    "string",
    "bool",
  };
}
/* JavaCC - OriginalChecksum=cf5b6731258e941347e7f0f29f626110 (do not edit this line) */
