/* Generated By:JavaCC: Do not edit this line. HLVisitor.java Version 7.0.10 */
public interface HLVisitor
{
  public Object visit(SimpleNode node, Object data) throws Exception;
  public Object visit(ASTvar_decl node, Object data) throws Exception;
  public Object visit(ASTfn_decl node, Object data) throws Exception;
  public Object visit(ASTparam_decls node, Object data) throws Exception;
  public Object visit(ASTvarparam node, Object data) throws Exception;
  public Object visit(ASTfunparam node, Object data) throws Exception;
  public Object visit(ASTbody node, Object data) throws Exception;
  public Object visit(ASTassignment node, Object data) throws Exception;
  public Object visit(ASTif_stat node, Object data) throws Exception;
  public Object visit(ASTNULL node, Object data) throws Exception;
  public Object visit(ASTclause node, Object data) throws Exception;
  public Object visit(ASTfor_stat node, Object data) throws Exception;
  public Object visit(ASTforeach_stat node, Object data) throws Exception;
  public Object visit(ASTwhile_stat node, Object data) throws Exception;
  public Object visit(ASTfn_call node, Object data) throws Exception;
  public Object visit(ASTparameters node, Object data) throws Exception;
  public Object visit(ASTreturn_stat node, Object data) throws Exception;
  public Object visit(ASTprint_stat node, Object data) throws Exception;
  public Object visit(ASTprintln_stat node, Object data) throws Exception;
  public Object visit(ASTor node, Object data) throws Exception;
  public Object visit(ASTand node, Object data) throws Exception;
  public Object visit(ASTnot node, Object data) throws Exception;
  public Object visit(ASTcomparison node, Object data) throws Exception;
  public Object visit(ASTLT node, Object data) throws Exception;
  public Object visit(ASTLE node, Object data) throws Exception;
  public Object visit(ASTGT node, Object data) throws Exception;
  public Object visit(ASTGE node, Object data) throws Exception;
  public Object visit(ASTEQ node, Object data) throws Exception;
  public Object visit(ASTNE node, Object data) throws Exception;
  public Object visit(ASTisint node, Object data) throws Exception;
  public Object visit(ASTispol node, Object data) throws Exception;
  public Object visit(ASTisfun node, Object data) throws Exception;
  public Object visit(ASTsum node, Object data) throws Exception;
  public Object visit(ASTplus node, Object data) throws Exception;
  public Object visit(ASTminus node, Object data) throws Exception;
  public Object visit(ASTproduct node, Object data) throws Exception;
  public Object visit(ASTtimes node, Object data) throws Exception;
  public Object visit(ASTdiv node, Object data) throws Exception;
  public Object visit(ASTeval node, Object data) throws Exception;
  public Object visit(ASTpolyn node, Object data) throws Exception;
  public Object visit(ASTidentifier node, Object data) throws Exception;
  public Object visit(ASTinteger node, Object data) throws Exception;
  public Object visit(ASTstring node, Object data) throws Exception;
  public Object visit(ASTbool node, Object data) throws Exception;
}
/* JavaCC - OriginalChecksum=c74305077db8c2c7d487095bd598a881 (do not edit this line) */
